for count in range (9):
    count = input("Input 10 number :")
    allnumbers = list(map(float, count.split()))
    length =len(allnumbers)
    s=sum(allnumbers)
    averagenums=float(s/length)
    print(aver)
    allnumbers.sort()
    print("difference between average number and smallest number",averagenums-allnumbers[0])
    print("difference between average number and largest number",allnumbers[length-1]-averagenums)