for x in range (9):
    x = input("Input 10 number :")
    numbers = list(map(float, x.split()))
    length =len(numbers)
    s=sum(numbers)
    aver=float(s/length)
    print(aver)
    numbers.sort()
    print("the difference between average number and smallest number",aver-numbers[0])
    print("the difference between average number and largest number",numbers[length-1]-aver)